### ISSUE TITLE
Why is Laminas\Twitter\Twitter now final?

### ISSUE THREAD

**Issue by shaneiseminger** [laminas/laminas-twitter#12]
### BC Break Report

|    Q        |   A
|------------ | ------
| Version     | 3.2.0

#### Summary

We have code that extends `Laminas\Twitter\Twitter`. Recently `composer update` bumped us from 3.1.1 to 3.2.0 and our code, of course, stopped working because that class is now `final`. I'm sure there's a reason for this change, but I can't spot what it is so I wanted to flag this usage (and maybe find out why the project doesn't want people extending this class anymore).

It would have been helpful if this change were part of a major version upgrade, and/or the breaking change was noted somewhere.

#### Previous behavior

We could extend this class.

#### Current behavior

We now cannot extend this class.

#### How to reproduce

Write a class that extends `Laminas\Twitter\Twitter` against 3.1.1. Update to 3.2.0.

**Comment by Ocramius** [comment]
Yep, that should not have been released as `3.2.0`.

Suggestion: release `3.2.1` with the `final` removed, move the `final` modifier to `4.0.0`

**Comment by shaneiseminger** [comment]
Thanks

Could someone explain why this class shouldn't be extended as of `4.0.0`?

**Comment by Ocramius** [comment]
It's a service: you can compose with it/use it, but inheritance is the wrong point-cut to add behavior to it.

In practice, if it isn't explicitly designed to be extended, you should not make it extensible.

**Comment by shaneiseminger** [comment]
OK, makes sense, thanks, will take that into account in the future.

**Comment by weierophinney** [comment]
Fixed with #13; release of 3.2.1 coming shortly.
