### ISSUE TITLE
Uncaught TypeError: method_exists()

### ISSUE THREAD

**Issue by joetm** [laminas/laminas-twitter#23]
### Bug Report

|    Q        |   A
|------------ | ------
| PHP  | 8.0.8
| laminas/laminas-twitter  | ^3.3

#### Summary

Some bug in status update method.

#### Current behavior

Crashes with error.

#### How to reproduce

I am running this example code with valid media ids and a valid $twitter object:

```
$result = $twitter->statusUpdate(
    '#firstpost',
    null,
    ['media_ids' => [$media_id1, $media_id2]]
);

```

Error:

GET /post_to_twitter.php - Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in /vendor/laminas/laminas-twitter/src/Twitter.php:273
Stack trace:
#0 /vendor/laminas/laminas-twitter/src/Twitter.php(273): method_exists()
#1 /post_to_twitter.php(51): Laminas\Twitter\Twitter->__call()
#2 {main}
  thrown in /vendor/laminas/laminas-twitter/src/Twitter.php on line 273
  
  
#### Expected behavior

No error.

**Comment by Ocramius** [comment]
Looks like `$this->oauthConsumer` wasn't set :thinking: 

The fact that `$this->oauthConsumer` could be `null` is quite weird.

**Comment by joetm** [comment]
Okay, I got it working. Looks like an error in the media upload example in the README.
I simply replaced $twitter->statusUpdate() with $twitter->status**es**Update().

**Comment by Ocramius** [comment]
Would you be able to send a patch to fix the docs?

**Comment by Xerkus** [comment]
This package is now abandoned
