### ISSUE TITLE
"Cannot use object of type Laminas\OAuth\Config\StandardConfig as array" Error when Verifying Credentials

### ISSUE THREAD

**Issue by gburetz** [laminas/laminas-twitter#6]
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 3.1.0

#### Summary

Verifying credentials results in the following error: Cannot use object of type Laminas\OAuth\Config\StandardConfig as array

#### How to reproduce

Update to latest version of all dependencies and attempt to verify credentials (At time of reporting, "laminas-http: 2.14.3, laminas-oauth: 2.1.0).
Rolling back to laminas-http 2.13 and laminas-oauth 2.0.3 restores correct function.

`$twitter = new Twitter( [
            'access_token' => [
                'token' => $token,
                'secret' => $tokenSecret,
            ],
            'oauth_options' => [
                'consumerKey' => $consumer_key,
                'consumerSecret' => $consumer_secret,
            ],
        ] );`

`$result = $twitter->accountVerifyCredentials()->toValue();`

This issue more likely directly relates to laminas-http or laminas-oauth, but both of those packages used by this one are in security-only maintenance mode.

**Comment by weierophinney** [comment]
Fixed with laminas/laminas-oauth#11 (I chose to go ahead and patch that one, as the issue was introduced in the last release prior to marking it security-only).

**Comment by weierophinney** [comment]
(laminas/laminas-oauth 2.1.1 contains the fix)
